const portfolio = {
 contact: { email: 'elifnurtekay29@gmail.com' },
 highlights: [{ value: '3', label: 'academic publications' }, { value: 'Best Student Paper', label: 'INFUS 2026' }, { value: '2nd / 800 teams', label: 'Turkcell competition' }, { value: 'TUSAŞ LIFT UP', label: 'capstone project' }],
 experience: [
  { period: 'Aug 2024 – Present', role: 'Research Assistant', organization: 'ANLAM-NET Research LAB, Ankara University', description: 'Research assistance spanning multimodal memorability and AI engineering work.' },
  { period: 'Jul 2025 – Aug 2025', role: 'Artificial Intelligence Applications Unit Intern', organization: 'TÜBİTAK SAGE', description: 'Worked on AI applications during a research internship.' },
  { period: 'Mar 2025 – Jun 2025', role: 'Part-Time Student Employee', organization: 'Ankara University Project Support Office', description: 'Supported the Project Support Office as a student employee.' },
  { period: 'Jul 2024 – Aug 2024', role: 'Intern', organization: 'SA Innovation', description: 'Completed an engineering internship.' }
 ],
 projects: [
  { id:'memovision', title:'MemoVision', subtitle:'Video and Brand Memorability Platform', categories:['Artificial Intelligence','Research'], status:'Completed', year:'2025–2026', summary:'An end-to-end research and competition project connecting video and brand memorability models to a working web interface.', challenge:'Make multimodal memorability prediction accessible through a user-facing workflow.', contribution:'Contributed to an AI product demonstrated through TÜBİTAK 2209-A research and the Turkcell competition.', approach:'Video and brand memorability prediction with a web interface for model-to-user interaction.', outcomes:'Second place among 800 teams in Turkcell Yarının Teknoloji Liderleri.', technologies:['Python','Deep Learning','Multimodal Learning','Web Interface'], awards:['Second Place — Turkcell Yarının Teknoloji Liderleri, 2026'], privacyStatus:'Research Project · Demo Not Publicly Available', featured:true, image:null, imageAlt:'MemoVision project documentation placeholder', imageWidth:1200, imageHeight:675 },
  { id:'airfoil-rl', title:'Aerodynamic Shape Optimisation Using Reinforcement Learning', subtitle:'TUSAŞ LIFT UP Capstone Project', categories:['Artificial Intelligence','Research','Aerospace','Academic'], status:'Completed', year:'2025–2026', summary:'CST-based airfoil optimisation using reinforcement learning, surrogate models, aerodynamic validation, and explainability analysis.', challenge:'Optimise airfoil geometry while respecting aerodynamic and geometric constraints.', contribution:'Built project outputs into a working web interface and applied SHAP to explain trained-policy decisions.', approach:'PPO, TD3, and SAC with hybrid surrogate models; XFOIL and NeuralFoil validation; CST geometry representation.', outcomes:'Produced INFUS 2026 Best Student Paper Award-winning work and earned first place in Ankara University’s AI and Data Science category.', technologies:['Python','PPO','TD3','SAC','XFOIL','NeuralFoil','SHAP'], awards:['Best Student Paper Award — INFUS 2026','First Place — Ankara University AI and Data Science, May 2026'], privacyStatus:'Academic Project · Demo Not Publicly Available', featured:true, image:null, imageAlt:'Airfoil reinforcement learning project documentation placeholder', imageWidth:1200, imageHeight:675 },
  { id:'teknofest', title:'TEKNOFEST Aviation AI Competition', subtitle:'Aviation AI Competition Work', categories:['Artificial Intelligence','Computer Vision','Ongoing'], status:'Ongoing', year:'2026–Present', summary:'Python-based integration, inference, evaluation, performance analysis, and output validation for aviation AI tasks.', challenge:'Address UAV and helicopter detection/tracking, camera-based position estimation, and reference object detection.', contribution:'Collaborative Git/GitHub-based engineering work on inference and evaluation workflows.', approach:'Python-based model integration and validation; final selected algorithms are not yet public.', outcomes:'Ongoing competition work.', technologies:['Python','Computer Vision','Git','GitHub'], awards:[], privacyStatus:'Private Repository · Ongoing Competition Work', featured:true, image:null, imageAlt:'TEKNOFEST aviation AI project documentation placeholder', imageWidth:1200, imageHeight:675 },
  { id:'bap', title:'AI-Based Perception, Tracking, and Position Estimation for Autonomous Aerial Vehicles', subtitle:'Ankara University BAP Project', categories:['Artificial Intelligence','Computer Vision','Research','Ongoing'], status:'Ongoing', year:'Ongoing', summary:'A distinct ongoing BAP project focused on visual perception, tracking, and camera-based position estimation for autonomous aerial vehicles.', challenge:'Develop visual processing for autonomous aerial-vehicle contexts.', contribution:'Ongoing project work in object detection, tracking, and camera-based position estimation.', approach:'Visual processing and AI engineering workflows.', outcomes:'Ongoing research project.', technologies:['Python','Computer Vision','Image Processing'], awards:[], privacyStatus:'Research Project · Demo Not Publicly Available', featured:true, image:null, imageAlt:'Autonomous aerial vehicles project documentation placeholder', imageWidth:1200, imageHeight:675 },
  { id:'realtime', title:'Real-Time Messaging and Calling Application', subtitle:'Full-Stack Communication Application', categories:['Full Stack','Completed'], status:'Completed', year:'Date not verified', summary:'A real-time application supporting messaging plus voice and video calls with a database-backed backend.', challenge:'Support low-latency communication features within a web application.', contribution:'Built a Node.js, WebSocket, WebRTC, and MySQL-based application.', approach:'Real-time events with WebSocket, media calling with WebRTC, and MySQL persistence.', outcomes:'Working academic web project.', technologies:['Node.js','WebSocket','WebRTC','MySQL'], awards:[], privacyStatus:'Academic Project · Repository Status Not Verified', featured:false, image:'assets/img/projects/rtc.png', imageAlt:'Real-time messaging and calling application interface', imageWidth:1536, imageHeight:864 },
  { id:'project-management', title:'Project Management Application', subtitle:'Full-Stack Team Workflow Application', categories:['Full Stack','Completed'], status:'Completed', year:'Date not verified', summary:'A project-management application for task assignment, progress tracking, team management, and Gantt chart visualisation.', challenge:'Bring team workflows and progress into a clear web interface.', contribution:'Developed with Django, MongoDB, React, and CSS.', approach:'Django and MongoDB backend paired with a React interface.', outcomes:'Working academic web project.', technologies:['Django','MongoDB','React','CSS'], awards:[], privacyStatus:'Academic Project · Screenshot Not Available', featured:false, image:null, imageAlt:'Project management application screenshot placeholder', imageWidth:1200, imageHeight:675 },
  { id:'attendance', title:'Student Attendance Application', subtitle:'Web-Based Attendance Management', categories:['Full Stack','Completed'], status:'Completed', year:'Date not verified', summary:'A web-based attendance management system developed with Python, Django, and SQLite3.', challenge:'Provide a web workflow for attendance management.', contribution:'Built the application using Django and SQLite3.', approach:'Python/Django web application with SQLite3 storage.', outcomes:'Working academic web project.', technologies:['Python','Django','SQLite3'], awards:[], privacyStatus:'Academic Project · Repository Status Not Verified', featured:false, image:'assets/img/projects/attendance.png', imageAlt:'Student attendance application interface', imageWidth:1536, imageHeight:864 },
  { id:'agendax', title:'AjandaX', subtitle:'Event and Appointment Management System', categories:['Full Stack','Completed'], status:'Completed', year:'Date not verified', summary:'An event and appointment management system with calendar viewing and reminder-supported time management.', challenge:'Make event and appointment management clear and accessible on the web.', contribution:'Developed create/edit workflows and calendar-based viewing.', approach:'Django and MongoDB with HTML, CSS, Bootstrap, and JavaScript.', outcomes:'Working academic web project.', technologies:['Django','MongoDB','JavaScript','Bootstrap'], awards:[], privacyStatus:'Academic Project · Repository Status Not Verified', featured:false, image:'assets/img/projects/agendax.png', imageAlt:'AjandaX event and appointment management interface', imageWidth:1536, imageHeight:864 },
  { id:'mediaeval', title:'Predicting Movie and Commercial Memorability', subtitle:'MediaEval 2025', categories:['Artificial Intelligence','Research','Academic'], status:'Completed', year:'2025', summary:'Research work on movie and commercial memorability prediction for MediaEval 2025.', challenge:'Study memorability prediction for digital media.', contribution:'Research and experimentation on memorability analysis.', approach:'Multimodal media analysis.', outcomes:'Related to MediaEval 2025 workshop proceedings.', technologies:['Machine Learning','Multimodal Learning'], awards:[], privacyStatus:'Research Project', featured:false, image:null, imageAlt:'MediaEval research project documentation placeholder', imageWidth:1200, imageHeight:675 },
  { id:'clip', title:'CLIP-Based Deep Learning Approaches for Digital Media Memorability Prediction', subtitle:'TÜBİTAK 2209-A Research', categories:['Artificial Intelligence','Research','Academic'], status:'Completed', year:'Date not verified', summary:'TÜBİTAK 2209-A-supported research into CLIP-based deep learning approaches for digital media memorability prediction.', challenge:'Explore deep-learning approaches to digital media memorability.', contribution:'Research project work.', approach:'CLIP-based deep learning approaches.', outcomes:'TÜBİTAK 2209-A-supported research.', technologies:['CLIP','Deep Learning','Computer Vision'], awards:[], privacyStatus:'Research Project', featured:false, image:null, imageAlt:'CLIP memorability research project documentation placeholder', imageWidth:1200, imageHeight:675 },
  { id:'mlp-vit', title:'Comparative Analysis of MLP and Vision Transformers for Video Memorability Classification', subtitle:'IEEE UBMK 2025 Research', categories:['Artificial Intelligence','Research','Academic'], status:'Completed', year:'2025', summary:'A comparative research study of MLP and Vision Transformer approaches for video memorability classification.', challenge:'Compare model families for video memorability classification.', contribution:'Research and publication work.', approach:'MLP and Vision Transformer comparison.', outcomes:'Published at IEEE UBMK 2025.', technologies:['MLP','Vision Transformers','Computer Vision'], awards:[], privacyStatus:'Research Project', featured:false, image:null, imageAlt:'Video memorability classification research documentation placeholder', imageWidth:1200, imageHeight:675 },
  { id:'yazan-zeka', title:'Helicopter and UAV Object Detection + Visual Odometry', subtitle:'GMKA “Yazan Zeka” Mentorship Program', categories:['Artificial Intelligence','Computer Vision','Research'], status:'Completed', year:'Date not verified', summary:'Mentorship-program work on helicopter and UAV object detection alongside visual odometry.', challenge:'Develop visual understanding workflows for aerial imagery.', contribution:'Project work on object detection and visual odometry.', approach:'Computer vision experimentation.', outcomes:'GMKA “Yazan Zeka” Mentorship Program project.', technologies:['Computer Vision','Object Detection','Visual Odometry'], awards:[], privacyStatus:'Academic Project · Repository Status Not Verified', featured:false, image:null, imageAlt:'Helicopter and UAV detection project documentation placeholder', imageWidth:1200, imageHeight:675 }
 ],
 publications:[{title:'Comparative Analysis of MLP and Vision Transformers for Video Memorability Classification',authors:'Elif Nur Tekay',venue:'IEEE UBMK',year:'2025',status:'Published',doi:'10.1109/UBMK67458.2025.11207010'},{title:'Multimodal Feature Fusion for Video and Brand Memorability',authors:'Elif Nur Tekay',venue:'MediaEval Workshop Proceedings',year:'2025',status:'Published',doi:''},{title:'Reinforcement Learning-Based Airfoil Shape Optimization Using Hybrid Surrogate Models',authors:'Elif Nur Tekay',venue:'INFUS',year:'2026',status:'Presented',doi:'',award:'Best Student Paper Award'}],
 awards:[{title:'Best Student Paper Award',organization:'INFUS 2026',year:'2026',related:'Reinforcement Learning-Based Airfoil Shape Optimization Using Hybrid Surrogate Models'},{title:'First Place — Artificial Intelligence and Data Science Category',organization:'Ankara University Informatics Project Market and Career Days',year:'May 2026',related:'Aerodynamic Shape Optimisation Using Reinforcement Learning'},{title:'Second Place — Turkcell Yarının Teknoloji Liderleri',organization:'Turkcell',year:'2026',related:'MemoVision · 2nd place among 800 teams'}],
 skills:[{category:'Languages',items:['Python','Java','C/C++','JavaScript','PHP','SQL','HTML','CSS']},{category:'Frontend & web',items:['React','Bootstrap','Responsive Design']},{category:'Backend',items:['Django','Node.js','WebSocket','WebRTC']},{category:'Databases',items:['PostgreSQL','MySQL','MongoDB','SQLite3']},{category:'AI & data',items:['Machine Learning','Deep Learning','Computer Vision','Image Processing','Reinforcement Learning','Explainable AI','GAN','Super-Resolution']},{category:'Engineering tools',items:['Git','GitHub','Docker','Postman','Linux','Google Colab','Visual Studio','VS Code']}],
 certificates:['Data Analysis School 2025–2026 — AI & Machine Learning Module','Web Development with Django — BTK Academy','C++ Programming — BTK Academy','Java Programming — BTK Academy','Deep Learning Bootcamp','Machine Learning Bootcamps — Akbank and Aygaz','Python Programming 401','White Hat Hacker — Siber Vatan','Introduction to Cybersecurity','Introduction to Linux and Networks — Cisco']
};

// Optional fields keep every project ready for a richer case study without
// creating placeholder links or duplicating component logic.
portfolio.projects.forEach((project) => Object.assign(project, {
  gallery: [], publicationLinks: [], repository: null, liveDemo: null
}, project));
